server:
    port: 8201
spring:
    application:
        name: service-hosp
#    cloud:
#        nacos:
#            discovery:
#                server-addr: 127.0.0.1:8848
#    data:
#        mongodb:
#            uri: mongodb://192.168.44.165:27017/yygh_hosp
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        password: root123
        url: jdbc:mysql://localhost:3306/yygh_hosp?characterEncoding=utf-8&useSSL=false
        username: root
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
    profiles:
        active: dev
#    rabbitmq:
#        host: 192.168.44.165
#        password: guest
#        port: 5672
#        username: guest
